<table style="width:680px;">
	<tr>
		<th>作業日時</th>
		<th>ログイン場所IP</th>
		<th>ログインマシン名</th>
		<th>ID</th>
		<th>内容</th>
	</tr>
    <?php foreach($this->items as $key=>$item): ?>
	<tr>
		<td><?php echo Qsoft_Helper_Datetime::time($item->created_at) ?></td>
		<td><?php echo $item->ip_address ?></td>
		<td><?php echo $item->login_pc_name ?></td>
		<td><?php echo $item->login_id ?></td>
		<td><?php echo $item->content ?></td>
	</tr>
    <?php endforeach; ?>
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="5"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>
</table>
<div class="form-action" style="width:680px;">
        <?php echo $this->items;?>
</div>