
<form name="point_config" method="post" action="<?php echo $this->url(array('action' => 'index')) ?>">
<table style="width:600px;">							
	<tr>
		<th colspan="5" style="padding:5px;">●<?php echo $this->translate('Point Provide') ?></th>
	</tr>
	<tr>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('No') ?></th>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('Action') ?></th>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('Content') ?></th>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('Event') ?></th>
		<th style="width:100px;padding:5px;"><?php echo $this->translate('Point Provide') ?></th>
	</tr>
	<tr>
		<td style="text-align:center;">1</td>
		<td style="text-align:center;"><?php echo $this->translate('Register') ?></td>
		<td style="text-align:center;"></td>
		<td style="text-align:center;"><?php echo $this->translate('Finish Register') ?></td>		
        <td><?php echo $this->form->regist_point ?></td>    
        </td>
	</tr>
	<tr>
		<td style="text-align:center;">2</td>
		<td style="text-align:center;"><?php echo $this->translate('Login') ?></td>
		<td style="text-align:center;"></td>
		<td style="text-align:center;"><?php echo $this->translate('Login successfully') ?></td>
		<td><?php echo $this->form->login_point ?></td>
	</tr>
	<tr>
		<th colspan="2">			
            <?php echo $this->form->submit ?>
		</th>
	</tr>
</table>
</form>