
<p style="color: red">Please do not test on the first 3 items (#1, #2, and #3)</p>
<?php echo $this->form ?>
<table style="width:680px;">
	<tr>
		<th><?php echo $this->translate('SEQ') ?></th>
		<th><?php echo $this->translate('Stamp Name') ?></th>
		<th><?php echo $this->translate('Stamp Image') ?></th>
        <th><?php echo $this->translate('Price') ?></th>
		<th><?php echo $this->translate('Public/Private') ?></th>		
	</tr>
    <?php foreach($this->items as $key=>$item): ?>
    <?php $class = ($item->show_hide == 0) ? 'delete' : 'normal' ?>    
	<tr class="<?php echo $class ?>" >
		<td style="text-align:center;">
            <a href="<?php echo $this->url(array('controller'=>'stamp', 'action'=>'modify', 'id'=>$item->stamp_id), null, true);?>">
            <?php echo $item->stamp_id ?>
            </a>
        </td>
        <td style="text-align:center;"><?php echo $item->stamp_name ?></td>
		<td style="text-align:center;">
            <?php if($item->getSmallImageUrl()): ?>
            <img src="<?php echo $item->getSmallImageUrl() ?>" width="30" />
            <?php endif; ?>
        </td>
        <td style="text-align:center;"><?php echo $item->point ?>pt</td>
		<td style="text-align:center;"><?php echo ($item->show_hide == 0) ? 'private' : 'public' ?></td>		
	</tr>
    <?php endforeach; ?>
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="5"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>	
</table>
<div class="form-action" style="width:680px;">
        <?php echo $this->items;?>
</div>
