
<div style="overflow-y:scroll;height:300px;width:880px;margin: 0 auto;">
    <table style="margin:0;">
    	<tr>
    		<th colspan="8" style="text-align:center;"><?php echo $this->translate('Send to user') ?></th>
    	</tr>
    	<tr>
    		<th style="width:80px;padding:5px;"><?php echo $this->translate('Internal ID') ?></th>
    		<th style="width:80px;padding:5px;"><?php echo $this->translate('User ID') ?></th>
    		<th style="width:100px;padding:5px;"><?php echo $this->translate('Nick name') ?></th>
    		<th style="width:50px;padding:5px;"><?php echo $this->translate('Avatar') ?></th>
    		<th style="width:110px;padding:5px;"><?php echo $this->translate('Created at') ?></th>
    		<th style="width:110px;padding:5px;"><?php echo $this->translate('Last access') ?></th>
    		<th style="width:110px;padding:5px;"><?php echo $this->translate('Price') ?></th>
    		<th style="width:110px;padding:5px;"><?php echo $this->translate('Point') ?></th>
    	</tr>
        <?php foreach($this->items as $key=>$item): ?>
    	<tr>
    		<td><?php echo $item->id ?></td>
    		<td><?php echo $item->user_id ?></td>
    		<td><?php echo $item->nick_name ?></td>
    		<td style="text-align:center;"><?php echo ($item->sex == 1) ? 'Male' : 'Female' ?></td>
    		<td style="text-align:center;"><?php echo Qsoft_Helper_Datetime::time($item->created_at) ?></td>
    		<td style="text-align:center;"><?php echo Qsoft_Helper_Datetime::time($item->last_access) ?></td>
    		<td style="text-align:right;">&nbsp;<?php echo $item->sum_purchase ?>&nbsp;pt</td>
    		<td style="text-align:right;"><?php echo $item->point ?>&nbsp;pt</td>
    	</tr>
        <?php endforeach; ?>
    </table>
</div>

<form method="post" action="<?php echo $this->url(array('action' => 'sendbroadcast')) .
        '?' . http_build_query($this->query)?>">
    <div style="height:200px;width:840px;margin: 0 auto;text-align:left;">
       <br />
	   <span style="font-size:12px;font-weight:bold;">● <?php echo $this->translate('Content') ?></span>
	   <br /><br />
       <textarea name="text" id="text" style="width:100%;height:70%;"></textarea>
    </div>
    <br />
    <input type="submit" name="" value="<?php echo $this->translate('Send Message') ?>" />
    
</form>