<form name="dice" method="post" action="<?php echo $this->url(array('action' => 'index')) ?>">
<table style="width:600px;">
    <tr>
    	<th><?php echo $this->translate('Dice') ?></th>
    	<th><?php echo $this->translate('Content') ?></th>
	</tr>
	<tr>
		<td style="text-align:center;">1</td>
		<td><?php echo $this->form->dice_title1 ?></td>
	</tr>
	<tr>
		<td style="text-align:center;">2</td>
		<td><?php echo $this->form->dice_title2 ?></td>
	</tr>
	<tr>
		<td style="text-align:center;">3</td>
		<td><?php echo $this->form->dice_title3 ?></td>
	</tr>
	<tr>
		<td style="text-align:center;">4</td>
		<td><?php echo $this->form->dice_title4 ?></td>
	</tr>
	<tr>
		<td style="text-align:center;">5</td>
		<td><?php echo $this->form->dice_title5 ?></td>
	</tr>
	<tr>
		<td style="text-align:center;">6</td>
		<td><?php echo $this->form->dice_title6 ?></td>
	</tr>
	<tr>
		<th colspan="2">
			<?php echo $this->form->submit ?>
		</th>
	</tr>
</table>
</form>