<?php //echo $this->form ?>
<table style="width:680px;">
	<tr>
		<th><?php echo $this->translate('SEQ') ?></th>
		<th><?php echo $this->translate('Item Type') ?></th>
		<th><?php echo $this->translate('Item Name') ?></th>
		<th><?php echo $this->translate('Item Image') ?></th>
		<th><?php echo $this->translate('Point') ?></th>
		<th><?php echo $this->translate('Public/Private') ?></th>
	</tr>
    <?php foreach($this->items as $key=>$item): ?>
    <?php $class = ($item->show_hide == 0) ? 'delete' : 'normal' ?>
	<tr class="<?php echo $class ?>" >
		<td style="text-align:center;">
            <a href="<?php echo $this->url(array('controller'=>'item', 'action'=>'modify', 'id'=>$item->item_title), null, true);?>">
            <?php echo $item->item_title ?>
            </a>
        </td>
		<td style="text-align:center;"><?php echo $item->item_type ?></td>
		<td style="text-align:center;"><?php echo $item->item_title ?></td>
		<td style="text-align:center;">
            <?php if($item->item_img): ?>
            <img src="<?php echo Dto_Item::getImageUrl($item->item_img) ?>" width="48" />
            <?php endif; ?>
        </td>
		<td style="text-align:center;"><?php echo $item->point.'pt' ?></td>
		<td style="text-align:center;"><?php echo ($item->show_hide == 0) ? 'private' : 'public' ?></td>
	</tr>
    <?php endforeach; ?>
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="6"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>		
</table>
<div class="form-action" style="width:680px;">
        <?php echo $this->items;?>
</div>