<?php echo $this->filterForm;?>
<table style="width:680px;">
	<tr>
		<th><?php echo $this->translate('Date') ?></th>
		<th><?php echo $this->translate('Time') ?></th>
		<th><?php echo $this->translate('Number') ?></th>
		<th><?php echo $this->translate('Point') ?></th>
	</tr>
    <?php foreach($this->items as $key=>$item): ?>
	<tr>
		<td><?php echo Qsoft_Helper_Datetime::dateView($item->created_at) ?></td>
		<td><?php echo Qsoft_Helper_Datetime::hour($item->created_at) ?></td>
		<td style="text-align:right;"><?php echo $item->sum_amount ?></td>
		<td style="text-align:right;">￥<?php echo $item->sum_point ?></td>
	</tr>
    <?php endforeach; ?>
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="4"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>	
</table>
<div class="form-action" style="width:680px;">
        <?php echo $this->items;?>
</div>