<?php echo $this->form ?>
<table style="width:680px;">
	<tr>
		<th style="width:80px;padding:5px;">SEQ</th>
		<th style="width:220px;padding:5px;">禁止語句</th>
		<th style="width:100px;padding:5px;">作成日時</th>
		<th style="width:100px;padding:5px;">更新日時</th>
		<th style="width:100px;padding:5px;">削除</th>
	</tr>
    <?php foreach($this->items as $key=>$item): ?>
	<tr>
		<td style="text-align:center;"><a href="<?php echo $this->url(array('controller'=>'wordnotgood', 'action'=>'modify', 'id'=>$item->id), null, true);?>"><?php echo $item->id ?></a></td>
		<td><?php echo $item->word ?></td>
		<td style="text-align:center;"><?php echo Qsoft_Helper_Datetime::time($item->created_at) ?></td>
		<td style="text-align:center;"><?php echo Qsoft_Helper_Datetime::time($item->updated_at) ?></td>
		<td style="text-align:center;"><input type='button' value='Delete' onclick="goConfirm('Do you want to delete ?','<?php echo $this->url(array('action' => 'delete', 'id' => $item->id)) ?>');" /></td>
	</tr>
    <?php endforeach; ?>
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="5"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>
</table>
<div class="form-action">
        <?php echo $this->items;?>
</div>