<table style="width:680px;">
	<tr>
		<th style="width:80px;padding:5px;">ID</th>
		<th style="width:120px;padding:5px;"><?php echo $this->translate('Password') ?></th>
		<th style="width:150px;padding:5px;"><?php echo $this->translate('Admin user name') ?></th>
		<th style="width:150px;padding:5px;"><?php echo $this->translate('Role name') ?></th>
		<th style="width:100px;padding:5px;"><?php echo $this->translate('State') ?></th>
	</tr>
    <?php foreach ($this->items as $key=>$item): ?>
	<tr>
		<td style="text-align:left;"><a href="<?php echo $this->url(array('controller'=>'admin-user','action'=>'modify','id'=>$item->admin_user_id)) ?>"><?php echo $item->admin_user_id ?></a></td>
		<td style="text-align:left;">******</td>
		<td style="text-align:left;"><?php echo $item->admin_user_name ?></td>
		<td style="text-align:left;"><?php echo $item->role_name ?></td>
		<td style="text-align:left;"><?php echo ($item->delete_flg == Dto_AdminUser::ADMIN_STATE_VALID) ? $this->translate('Valid') : $this->translate('Invalid')  ?></td>
	</tr>
    <?php endforeach; ?>
    
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="6"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>
</table>
<div class="form-action" style="width:680px;">
        <?php echo $this->items;?>
</div>