<?php echo $this->filterForm;?>
<table style="width:880px;">
	<tr>
		<th><?php echo $this->translate('Date') ?></th>
		<th><?php echo $this->translate('User report') ?></th>
		<th><?php echo $this->translate('Target') ?></th>
		<th><?php echo $this->translate('Content') ?></th>
		<th><?php echo $this->translate('Reply') ?></th>
		<th><?php echo $this->translate('Reply') ?></th>
	</tr>
    
    <?php foreach($this->items as $item): ?>
	<tr>
		<td><?php echo Qsoft_Helper_Datetime::time($item->created_at) ?></td>
		<td><a href="<?php echo $this->url(array('controller'=>'user','action'=>'modify','id'=>$item->report_user_id )) ?>"><?php echo $item->user_report_nick_name ?></a></td>
		<td><a href="<?php echo $this->url(array('controller'=>'user','action'=>'modify','id'=>$item->target_user_id )) ?>"><?php echo $item->user_target_nick_name ?></a></td>
		<td><?php echo $item->content ?></td>
        <?php if($item->reply_flg == 0): ?>
        <td><a href="<?php echo $this->url(array('controller'=>'user-report','action'=>'send','id'=>$item->user_report_id )) ?>">返信する</a></td>
        <?php else: ?>
		<td>済</td>
        <?php endif; ?>
		<td><?php echo $item->reply ?></td>
	</tr>
    <?php endforeach; ?>
    
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="6"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>		
</table>
<div class="form-action" style="width:880px;">
        <?php echo $this->items;?>
</div>