<?php echo $this->filterForm;?>
<table style="width:600px;">
	<tr>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('Date') ?></th>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('User ID') ?></th>
		<th style="width:80px;padding:5px;"><?php echo $this->translate('Nick name') ?></th>
		<th style="width:100px;padding:5px;"><?php echo $this->translate('Content') ?></th>
	</tr>
    <?php foreach($this->items as $key=>$item): ?>
	<tr>
        <td><?php echo Qsoft_Helper_Datetime::time($item->created_at) ?></td>
        <td><?php echo $item->user_id_text ?></td>
        <td style="text-align:right;"><?php echo $item->nick_name ?></td>
        <td style="text-align:right;"><?php echo $item->content ?></td>
    </tr>
    <?php endforeach; ?>
    <?php if (count($this->items) < 1) : ?>
        <tr>
            <td colspan="4"><?php echo $this->translate("There are no items.");?></td>
        </tr>
    <?php endif; ?>
</table>
<div class="form-action" style="width:600px;">
        <?php echo $this->items;?>
</div>